# azure-pipelines.yml
trigger:
- main  # Adjust branch as necessary

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  pythonVersion: '3.8'
  appLocation: 'flask_app'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build job'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        addToPath: true
        # packageType: 'sdk'
        # version: '5.x'
        # installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install Dependencies'

- stage: Test
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run tests'
    steps:
    - script: |
        source venv/bin/activate
        pytest
      displayName: 'Run tests'

- stage: Deploy
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure App Service'
    steps:
    - task: UsePythonVersion@0
      inputs:
        azureSubscription: 'Pay-As-You-Go'
        appType: 'webApp'
        appName: 'myApp'
        versionSpec: '$(pythonVersion)'
        addToPath: true
