name: Trigger auto deployment for greet-sum-flask-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev, master ]
    paths:
    - '**'
    - '.github/workflows/greet-sum-flask-api-AutoDeployTrigger-da00ea7b-e056-47f7-82ad-d8573cd128dc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Static Code Analysis with pylint
        run: pylint --fail-under=8 app.py test_app.py

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GREETSUMFLASKAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GREETSUMFLASKAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GREETSUMFLASKAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: bluewebapps.azurecr.io
          registryUsername: ${{ secrets.GREETSUMFLASKAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GREETSUMFLASKAPI_REGISTRY_PASSWORD }}
          containerAppName: greet-sum-flask-api
          resourceGroup: greet-sum-flask-env
          imageToBuild: bluewebapps.azurecr.io/greet-sum-flask-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


