name: Trigger auto deployment for hello-sum-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/hello-sum-api-AutoDeployTrigger-422ca488-5bc7-47fe-987a-e8a7574004e9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Static Code Analysis with pylint
        run: pylint --fail-under=8 app.py test_app.py

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HELLOSUMAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HELLOSUMAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HELLOSUMAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: bluewebapps.azurecr.io
          registryUsername: ${{ secrets.HELLOSUMAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HELLOSUMAPI_REGISTRY_PASSWORD }}
          containerAppName: hello-sum-api
          resourceGroup: hello-sum-flask-env
          imageToBuild: bluewebapps.azurecr.io/hello-sum-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

  manual-approval:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.ref == 'refs/heads/dev' # Ensure this job only runs for the dev branch
    steps:
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          approvers: | 
            s-oluwade
          minimum-approvals: 1
          secret: ${{ github.TOKEN }}

  merge:
    runs-on: ubuntu-latest
    needs: manual-approval
    if: github.ref == 'refs/heads/dev' # Ensure this job only runs for the dev branch
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Merge dev into master
        uses: devops-infra/action-github-pull-request@v1
        with:
          title: 'Merge dev into master'
          body: 'Automated merge of dev into master'
          base: 'master'
          head: 'dev'
          github_token: ${{ secrets.GITHUB_TOKEN }}

